version: 2
jobs:
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                  # CircleCI上でSSHキー登録を行った際に作成されるfingerprintsを記入！！
                  - SHA256:N77ns23B/SIzeVcyWEcXW/+xE/+8+uSRldf3AXeyrsk
            #この箇所の［EC2上のプロジェクトパス］を自身のパスに書き換え！！
            - run: ssh ${USER_NAME}@${HOST_NAME} 'cd ［EC2上のプロジェクトパス］ && git pull'

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: main
