version: 2
jobs:
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                  - c9:9b:e6:d7:7f:de:19:5c:53:23:94:51:99:f6:5c:9f
            - run: ssh ${USER_NAME}@${HOST_NAME} 'cd ［ssh -i "family2.pem" ec2-user@ec2-43-206-181-167.ap-northeast-1.compute.amazonaws.com］ && git pull'

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: main
